// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/1/2025, 21:49:49
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/enyelberth/Github/gt-frontend-2024/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/enyelberth/Github/gt-frontend-2024/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/enyelberth/Github/gt-frontend-2024/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/enyelberth/Github/gt-frontend-2024/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/enyelberth/Github/gt-frontend-2024/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/enyelberth/Github/gt-frontend-2024/plugins/**/*.{js,ts,mjs}","/home/enyelberth/Github/gt-frontend-2024/composables/**/*.{js,ts,mjs}","/home/enyelberth/Github/gt-frontend-2024/utils/**/*.{js,ts,mjs}","/home/enyelberth/Github/gt-frontend-2024/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/enyelberth/Github/gt-frontend-2024/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/enyelberth/Github/gt-frontend-2024/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;