// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27/1/2025, 7:31:16 p.m.
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/PC/Documents/gt-frontend-2024/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/plugins/**/*.{js,ts,mjs}","C:/Users/PC/Documents/gt-frontend-2024/composables/**/*.{js,ts,mjs}","C:/Users/PC/Documents/gt-frontend-2024/utils/**/*.{js,ts,mjs}","C:/Users/PC/Documents/gt-frontend-2024/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;