// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27/1/2025, 11:32:33 a.m.
const configMerger = require("C:/Users/PC/Documents/gt-frontend-2024/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/PC/Documents/gt-frontend-2024/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/plugins/**/*.{js,ts,mjs}","C:/Users/PC/Documents/gt-frontend-2024/composables/**/*.{js,ts,mjs}","C:/Users/PC/Documents/gt-frontend-2024/utils/**/*.{js,ts,mjs}","C:/Users/PC/Documents/gt-frontend-2024/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PC/Documents/gt-frontend-2024/app.config.{js,ts,mjs}"] } }));

module.exports = config
